In [ ]:
# load the iris dataset as an example
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:

# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target

In [ ]:
# store the feature and target names
feature_names = iris.feature_names
target_names = iris.target_names

In [ ]:
#printing features and target names of our dataset
print("Features names:", feature_names)
print("Target names:", target_names)

Features names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [ ]:
# X and y are numpy arrays
print("\nType of X is:", type(X))


Type of X is: <class 'numpy.ndarray'>


In [ ]:
# printing first 5 input rows
print("\nFirst 5 rows of X:\n", X[:5])


First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


*Step:2*

In [ ]:
# load the iris dataset as an example
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target

In [ ]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [ ]:
# printing the shapes of the new X objects
print(X_train.shape)
print(X_test.shape)

(90, 4)
(60, 4)


In [ ]:
# printing the shapes of the new y objects
print(y_train.shape)
print(y_test.shape)

(90,)
(60,)


*TRAINING THE MODEL*

In [ ]:
# load the iris dataset as an example
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
# store the features matrix (X) and response vector (y)
X = iris.data
y = iris.target

In [ ]:
# spliting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [ ]:
# training the model on training set
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# making predicitions on the testing set
y_pred = knn.predict(X_test)

In [ ]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("kNN model accuracy:", metrics.accuracy_score(y_test, y_pred))

kNN model accuracy: 0.9833333333333333


In [ ]:
# making prediction for out of sample data
sample = [[3, 5, 4, 2] ,[2, 3, 5, 4]]
preds = knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("Predictions:", pred_species)

Predictions: ['versicolor', 'virginica']


In [ ]:
import joblib

In [ ]:
# saving the model
from sklearn.externals import joblib
joblib.dump(knn, 'iris_knn.pkl')

ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.10/dist-packages/sklearn/externals/__init__.py)